name: Trigger auto deployment for llm-council-containerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/llm-council-containerapp-AutoDeployTrigger-1af46e63-0e31-47b1-affd-46c174b0cb15.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.LLMCOUNCILCONTAINERAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.LLMCOUNCILCONTAINERAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.LLMCOUNCILCONTAINERAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./Dockerfile
          acrName: aicoellm
          containerAppName: llm-council-containerapp
          resourceGroup: RG-Environment9
          imageToBuild: aicoellm.azurecr.io/llm-council:${{ github.sha }}


